### ISSUE TITLE
Undefined OS but kernel is recognized correctly?

### ISSUE THREAD

**Issue by sh9r** [qwool/koghi#1]
Seems like the program can recognize I'm using an arch kernel, but not the Arch Distro
![image](https://github.com/qwool/koghi/assets/77307545/92d0b604-559b-4604-82f8-20d6c42b384d)

**Comment by if-not-nil** [comment]
looks like it doesnt find the right fields in /etc/lsb-release which isnt there by default on some distros
ill just switch it to /etc/os-release bc its standard

**Comment by if-not-nil** [comment]
fixed commit 9dfcd98!! and thanks for using this im glad i didnt make it for noting

**Comment by sh9r** [comment]
haha. i set fetch as an alias for koghi cause it looks nice haha

**Comment by sh9r** [comment]
How would I update it after moving it co `/usr/bin`?

**Comment by if-not-nil** [comment]
> haha. i set fetch as an alias for koghi cause it looks nice haha

oh wow! glad to hear this
> How would I update it after moving it co /usr/bin?

same as regular instructions, i think you do a ```git pull``` in source folder to update the repo and then do the same steps of  
```go build && sudo cp ./koghi /usr/bin/```

or theres a ./koghi binary included in repo if u dont wanna build anything but i wouldnt recommend taking random binaries from strangers like that
